services:
  # 1. BASE DE DATOS (PostgreSQL)
  postgres_db:
    image: postgres:15-alpine
    container_name: gym_postgres_db
    restart: always
    environment:
      POSTGRES_USER: estmk1995     # Cambia esto por tus credenciales
      POSTGRES_PASSWORD: est19952030
      POSTGRES_DB: elemental_database
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U estmk1995 -d elemental_database"]
      interval: 5s
      timeout: 5s
      retries: 5

  # 2. ADMINISTRADOR DE BD (pgAdmin)
  pgadmin:
    image: dpage/pgadmin4
    container_name: elemental_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ecjarac@puce.edu.ec # Credenciales para entrar al navegador
      PGADMIN_DEFAULT_PASSWORD: est19952030
    ports:
      - "5050:80"
    depends_on:
      postgres_db:
        condition: service_healthy

  # 3. BACKEND (Express + Sequelize)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: gym_backend
    restart: always
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
      - DB_HOST=postgres_db # Se usa el nombre del servicio de arriba como HOST
      - DB_USER=estmk1995
      - DB_PASS=est19952030
      - DB_NAME=elemental_database
      - JWT_SECRET=ElementalCrossTraining_Secret_Key_2026
      - PORT=4000
    command: pnpm start
    depends_on:
      postgres_db:
        condition: service_healthy # Espera obligatoriamente a que la BD esté lista

  # 4. FRONTEND (React + Vite)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: elemental_frontend
    restart: always
    ports:
      - "5173:5173"
    command: pnpm dev -- --host 0.0.0.0
    environment:
      - VITE_API_URL=http://localhost:4000/api
    depends_on:
      - backend # Espera a que el backend esté arriba

volumes:
  postgres_data:
