FROM node:20-alpine

WORKDIR /app

# Copiar archivos de dependencias para aprovechar la caché de Docker
COPY package*.json ./

RUN npm install

# Copiar el resto del código fuente del backend
COPY . .

EXPOSE 4000

# Usamos nodemon (asumiendo que está en tu package.json) para desarrollo en vivo
CMD ["npm", "run", "dev"]